INSERT INTO SourceText (
INSERT INTO Class (id, name, base_class_id)
VALUES (1, "Bard"),
       (2, "Cleric"),
       (3, "Cleric (Knowledge)", 2),
       (4, "Cleric (Life)", 2),
       (5, "Cleric (Light)", 2),
       (6, "Cleric (Nature)", 2),
       (7, "Cleric (Tempest)", 2),
       (8, "Cleric (Trickery)", 2),
       (9, "Cleric (War)", 2),
       (10, "Cleric (Death)", 2),
       (11, "Druid"),
       (12, "Druid (Arctic)", 11),
       (13, "Druid (Coast)", 11),
       (14, "Druid (Desert)", 11),
       (15, "Druid (Forest)", 11),
       (16, "Druid (Grassland)", 11),
       (17, "Druid (Mountain)", 11), 
       (18, "Druid (Swamp)", 11),
       (19, "Druid (Underdark)", 11),
       (20, "Paladin"),
       (21, "Paladin (Ancients)", 20),
       (22, "Paladin (Devotion)", 20),
       (23, "Paladin (Vengence)", 20),
       (24, "Ranger"),
       (25, "Sorcerer"),
       (26, "Warlock"),
       (27, "Warlock (Archfey)", 26),
       (28, "Warlock (Fiend)", 26),
       (29, "Warlock (Great Old One)", 26),
       (30, "Wizard"),
);


